## 1. 🧠 What is NumPy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

**What you'll learn, in order:**
1. 🧠 What is NumPy?
2. ⚖️ NumPy Arrays vs Python Sequences
3. 🏗️ Creating NumPy Arrays
4. 📐 Array Attributes
5. 🔁 Changing Datatype
6. ➕ Array Operations
7. 📊 Array Mathematical Functions
8. 📈 Statistical Functions
9. 🎯 Indexing and Slicing *(+ 9.1 Slicing in Array, 9.2 Boolean & Fancy Indexing)*
10. 🔄 Iterating in NumPy Array
11. 🧩 Reshaping
12. 🔗 Stacking
13. ✂️ Splitting
14. ✅ Key Takeaways

> **In short:** NumPy stores numbers in tightly-packed grids called **arrays** and does math on the whole grid at once using fast, pre-compiled C code under the hood — this is why NumPy is often 10-100x faster than plain Python loops for numeric work.

**More examples — flexible input types:**

In [ ]:
import numpy as np

# np.array() accepts tuples, ranges, and even other arrays -- not just lists
print(np.array((1, 2, 3)))    # from a tuple
print(np.array(range(5)))     # from a range object

In [ ]:
# same numbers, different types
print(type([1, 2, 3]))
print(type(np.array([1, 2, 3])))

## 2. ⚖️ NumPy Arrays vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

**Quick example — the #1 beginner trap:** `*` means something completely different for a list vs an array.

In [ ]:
import numpy as np

list_a = [1, 2, 3]
arr_a = np.array([1, 2, 3])

print(list_a * 2)   # [1, 2, 3, 1, 2, 3]  -> repeats the list
print(arr_a * 2)    # [2 4 6]             -> multiplies every element

**More examples — the fixed-size & same-dtype rules in action:**

In [ ]:
arr = np.array([1, 2, 3])
try:
    arr.append(4)   # lists have .append(), arrays don't
except AttributeError as e:
    print("Error:", e)

In [ ]:
# mixing types: NumPy picks ONE dtype for everything (upcasting)
mixed = np.array([1, 2, 3.5])          # ints + float -> all become float
print(mixed, mixed.dtype)

mixed_str = np.array([1, 2, "three"])  # any string present -> all become strings
print(mixed_str, mixed_str.dtype)

## 3. 🏗️ Creating NumPy Arrays

**Ways to create an array**, roughly most-to-least common:
- `np.array(list)` — from data you already have
- `np.arange(start, stop, step)` — like Python's `range()`
- `np.zeros(shape)` / `np.ones(shape)` — placeholders to fill in later
- `np.random.random(shape)` — random test data
- `np.linspace(start, stop, count)` — evenly spaced points
- `np.identity(n)` — identity matrix, used in linear algebra

In [1]:
# for downloading the packages
# !pip install --index-url https://pypi.apple.com/simple numpy pandas

In [2]:
import numpy as np

a = np.array([1,2,3]) ## 1D Array
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
# 2D List Array
b = np.array([[1,2,3],[4,5,6]])
print(b) ## Called as matrices

[[1 2 3]
 [4 5 6]]


In [4]:
# 3D List Array
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
# dtype - float
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [6]:
# dtype - bool
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [7]:
# dtype - complex
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

**Why set `dtype` explicitly?** It controls both memory usage and what kind of math you can do — e.g. force `float` when you'll need decimals later, or `bool` to store a True/False mask.

In [8]:
# np.arange
np.arange(1,15,2) ## (start,end,gap)

array([ 1,  3,  5,  7,  9, 11, 13])

`np.arange(start, stop, step)` behaves exactly like Python's built-in `range()` — `stop` is *never* included — except it hands back a NumPy array instead of a lazy range object.

In [9]:
# with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [10]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Reshape rule:** the new shape must hold the *same total number of elements* as before. 9 numbers can become (3,3), (1,9), or (9,1) — but never (3,4), since 12 slots ≠ 9 numbers.

In [11]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.zeros((3,4)) ## np.zeroes used in neural network and deep learning

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
# np.random
np.random.random((3,4))  ## np.random.random(lower, upper)

array([[0.54413147, 0.02898731, 0.42510243, 0.8605604 ],
       [0.23980798, 0.00781589, 0.8921268 , 0.20216897],
       [0.04754743, 0.77369578, 0.694717  , 0.46698726]])

In [14]:
# np.linspace
np.linspace(-10,10,10,dtype=int)   ## np.linspace(lower, upper, count)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

**`arange` vs `linspace`:** `arange` lets you pick the *step size* (gap between numbers); `linspace` lets you pick *how many* numbers you want, and NumPy works out the spacing for you.

In [15]:
# np.identity
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

`np.identity(n)` makes an n×n grid with 1s on the diagonal and 0s everywhere else — the matrix equivalent of the number 1 (multiplying by it changes nothing).

**More ways to create arrays:**

In [ ]:
# np.full: fill an array with any constant value (not just 0 or 1)
np.full((2,3), 7)

In [ ]:
# np.eye: like np.identity, but lets you offset the diagonal
print(np.eye(4))          # same as identity(4)
print(np.eye(4, k=1))     # 1s shifted one column to the right

## 4. 📐 Array Attributes

**Attributes vs methods:** `.shape`, `.ndim`, `.size`, `.dtype`, `.itemsize` are *attributes* — no `()` at the end, they just describe the array. Things like `.reshape()` or `.astype()` are *methods* that do work, and need `()`.

| Attribute | Tells you |
|---|---|
| `.ndim` | how many dimensions |
| `.shape` | size along each dimension |
| `.size` | total number of elements |
| `.dtype` | data type of the elements |
| `.itemsize` | bytes used per element |

In [16]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [17]:
# ndim
print(a1.ndim) # 1D Array
print(a2.ndim) # 2D Array
print(a3.ndim) # 3D Array

1
2
3


In [18]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [19]:
# shape
print(a2.shape)
a2

(3, 4)


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [20]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [21]:
# itemsize
print(a1.itemsize) # 32bit int
print(a3.itemsize) # 64bit int

4
8


Smaller dtypes save memory but hold a smaller range of numbers. `int32` (4 bytes) holds roughly ±2 billion; `int64` (8 bytes) holds a vastly bigger range but uses twice the memory per number.

In [22]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


**More attribute examples:**

In [ ]:
# .nbytes = total memory used by the WHOLE array (itemsize * size)
print(a2.itemsize, a2.size, a2.itemsize * a2.size)
print(a2.nbytes)

In [ ]:
# attributes update automatically after reshaping -- they describe the CURRENT shape
b = np.arange(24)
print(b.shape, b.ndim)
b = b.reshape(2,3,4)
print(b.shape, b.ndim)

## 5. 🔁 Changing Datatype

`.astype()` always makes a **new, separate copy** — the original array is untouched. Watch out: converting `float → int` **truncates** (chops off) the decimal part, it does not round (`3.9` becomes `3`, not `4`).

In [23]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [24]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [25]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [26]:
# astype
a3.astype(np.int32) # use to save the space

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [27]:
np.info

<function numpy.info(object=None, maxwidth=76, output=None, toplevel='numpy')>

**More astype examples:**

In [ ]:
# strings that look like numbers can be converted to actual numbers
nums_as_text = np.array(["1", "2", "3"])
print(nums_as_text.dtype)
print(nums_as_text.astype(int))

In [ ]:
# int -> bool: any non-zero number becomes True, only 0 becomes False
np.array([0, 1, 2, -5]).astype(bool)

## 6. ➕ Array Operations

Two kinds of operations: **scalar** (array + a single number, e.g. `a * 2`) applies the same way to every element; **vector** (array + array) works *element by element*, and normally needs matching shapes — unless "broadcasting" kicks in (see below).

| Type | Example | What happens |
|---|---|---|
| Scalar | `a * 2` | every element ×2 |
| Scalar | `a ** 2` | every element squared |
| Vector | `a1 + a2` | element-by-element add (same shape) |
| Relational | `a > 15` | element-by-element compare → boolean mask |

In [28]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [29]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [31]:
# scalar operations
print(a1)
# arithmetic
a1 ** 2 ## square

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [32]:
# relational
print(a2)
a2 == 15

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [33]:
print(a2)
a2 > 15

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

Comparisons like `==`, `>`, `<` don't return a single True/False — they return a whole array of True/False values, one per element. This is called a **boolean mask**, and it's the key to filtering data (see *Boolean & Fancy Indexing* further down).

In [34]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

**Gotcha — integer overflow:** notice some results above are enormous, and one is even negative! `int64` can only hold values up to about 9.2×10¹⁸ — once `a1 ** a2` goes past that, the value silently wraps around into nonsense/negative territory instead of raising an error. If results can get this large, use a `float` dtype instead.

In [35]:
print(a1 + a2)
a1 + a2

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

**Broadcasting:** NumPy can still do vector operations even when array shapes don't match exactly, by mentally "stretching" the smaller one to fit — no need to manually copy it into the same shape yourself.

In [ ]:
row = np.arange(4)                  # shape (4,)
grid = np.arange(12).reshape(3, 4)  # shape (3,4)

print(row)
print(grid + row)   # row is broadcast: added to EVERY row of grid
print(grid + 10)     # a single number is broadcast to every element too

**More operation examples:**

In [ ]:
# division: NumPy follows true division by default (like Python 3's /)
print(a1 / 2)     # true division -> floats
print(a1 // 2)    # floor division -> whole numbers

In [ ]:
# chain a comparison mask straight into indexing to filter values
print(a1[a1 % 3 == 0])   # every element in a1 that's divisible by 3

## 7. 📊 Array Mathematical Functions

These functions summarize the whole array into fewer numbers (or just one). Most accept an `axis` argument so you can summarize *per row* or *per column* instead of the entire array — see the mnemonic below.

| Function | What it gives you |
|---|---|
| `np.max` / `np.min` | largest / smallest value |
| `np.sum` / `np.prod` | total sum / total product |
| `np.mean` / `np.median` | average / middle value |
| `np.std` / `np.var` | spread of the values |

In [36]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[53., 31., 94.],
       [ 8., 21., 99.],
       [33., 18.,  4.]])

In [37]:
np.max(a1)

np.float64(99.0)

In [38]:
np.min(a1)

np.float64(4.0)

In [39]:
np.sum(a1)

np.float64(361.0)

In [40]:
np.prod(a1)

np.float64(6103182121344.0)

In [41]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.max(a1,axis=0) ## column vise

array([53., 31., 99.])

In [42]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.max(a1,axis=1) ## row wise (one result per row)

array([94., 99., 33.])

In [43]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1,axis=0)

array([13992., 11718., 37224.])

**Axis mnemonic:** `axis=0` walks *down* the rows, collapsing them → one result **per column**. `axis=1` walks *across* the columns, collapsing them → one result **per row**. If unsure, check the output shape — it tells you which axis disappeared.

**More math function examples:**

In [ ]:
# cumsum/cumprod: running totals, one step at a time
b = np.array([1,2,3,4])
print(np.cumsum(b))    # [1, 3, 6, 10]
print(np.cumprod(b))   # [1, 2, 6, 24]

In [ ]:
# clip: force every value into a fixed range
np.clip(a1, 3, 8)   # anything below 3 becomes 3, anything above 8 becomes 8

## 8. 📈 Statistical Functions

`mean` = average. `median` = the middle value when sorted. `std` (standard deviation) and `var` (variance) both measure spread — `var` is just `std` squared. Low = numbers are close together; high = numbers are spread out.

In [44]:
np.mean(a1, axis=0)

array([31.33333333, 23.33333333, 65.66666667])

In [45]:
# mean/median/std/var
np.var(a1,axis=1)

array([ 681.55555556, 1614.88888889,  140.22222222])

In [46]:
# trigonomoetric functions
np.sin(a1)

array([[ 0.39592515, -0.40403765, -0.24525199],
       [ 0.98935825,  0.83665564, -0.99920683],
       [ 0.99991186, -0.75098725, -0.7568025 ]])

In [47]:
# dot product
a2 = np.arange(12).reshape(3,4)

In [48]:
a3 = np.arange(12,24).reshape(4,3)

In [49]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

`np.dot` performs real **matrix multiplication**, not element-wise multiplication. Rule: to multiply A·B, A's number of columns must equal B's number of rows. Here (3,4)·(4,3) → result shape (3,3).

In [50]:
# log and exponents
np.exp(a1)

array([[1.04137594e+23, 2.90488497e+13, 6.66317622e+40],
       [2.98095799e+03, 1.31881573e+09, 9.88903032e+42],
       [2.14643580e+14, 6.56599691e+07, 5.45981500e+01]])

In [51]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[50., 29., 49.],
       [60., 34., 11.]])

**Filling the gaps — median, std, and percentile:**

In [ ]:
print(np.median(a1))   # middle value when sorted
print(np.std(a1))      # standard deviation (spread)

In [ ]:
print(np.percentile(a1, 50))   # 50th percentile == median
print(np.percentile(a1, 90))   # value below which 90% of the data falls

## 9. 🎯 Indexing and Slicing

**Indexing** picks out a single element (`a[2,1]`). **Slicing** picks out a *range* of elements (`a[1:3]`) and always returns an array back, even if it ends up with just one row/column.

In [52]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [53]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
a1[0].item()

0

In [55]:
a1[0:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [56]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
a2[2,1].item()  ## [row, col] -> row 2, column 1

9

In [58]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [59]:
a3[1,0,1].item() # index order is [depth, row, col] -> depth 1, row 0, col 1

5

In [60]:
a3[1,1,0].item()

6

In [61]:
a3[0,0,1].item()

1

In [62]:
a3[1,1,0].item()

6

**Negative indexing — counting from the end:**

In [ ]:
print(a1[-1])        # last element
print(a2[-1, -1])    # last row, last column

In [ ]:
print(a3[-1])           # last "depth slice"
print(a3[-1, -1, -1])   # last element overall

### 9.1 ✂️ Slicing in Array

In [63]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
a1[2:5]

array([2, 3, 4])

In [65]:
a1[2:5:2]

array([2, 4])

In [66]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [68]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [69]:
a2[1,::3]

array([4, 7])

In [70]:
a2[0,:]

array([0, 1, 2, 3])

In [71]:
a2[:,2]

array([ 2,  6, 10])

In [72]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [73]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [74]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [75]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [76]:
a3[0,1,:]

array([3, 4, 5])

**Reversing with a negative step:**

In [ ]:
print(a1[::-1])       # whole array, reversed
print(a1[5:1:-1])     # partial reverse slice

In [ ]:
print(a2[::-1])        # rows reversed
print(a2[:, ::-1])     # columns reversed

### 9.2 🔍 Boolean & Fancy Indexing
Two more powerful ways to pick elements, beyond plain slicing:
- **Boolean indexing** — pass a True/False mask (like the one from `a2 > 15` earlier) to keep only the matching elements.
- **Fancy indexing** — pass a list of indices to pick out several specific elements at once, in any order.

In [ ]:
nums = np.arange(20)

# Boolean indexing: keep only values greater than 12
mask = nums > 12
print(mask)         # array of True/False
print(nums[mask])   # only the True positions survive

# Fancy indexing: grab specific positions directly
print(nums[[0, 5, 19]])   # elements at index 0, 5, and 19

**`np.where()` — get positions, not just values:**

In [ ]:
nums = np.arange(20)
idx = np.where(nums > 12)
print(idx)          # a tuple of index arrays where the condition is True
print(nums[idx])    # using those indices to fetch the values (same as nums[nums>12])

In [ ]:
# np.where can also pick between two values based on a condition
np.where(nums % 2 == 0, "even", "odd")

## 10. 🔄 Iterating in NumPy Array

A Python `for` loop over a NumPy array works, but it's slow on large arrays because each step drops back into regular (slow) Python. Prefer the vectorized functions above (`np.sum`, `a * 2`, etc.) whenever possible — save loops for small arrays or quick debugging.

In [77]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [78]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [79]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [80]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [81]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [82]:
for i in np.nditer(a3): ## convert array in 1D
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


**Iterating with index positions using `np.ndenumerate`:**

In [ ]:
for index, value in np.ndenumerate(a2):
    print(index, value)

In [ ]:
# plain enumerate() also works row-by-row for 2D+ arrays
for i, row in enumerate(a2):
    print(f"row {i}: {row}")

## 11. 🧩 Reshaping

Reshaping rearranges the *same* data into a new shape (nothing is added, removed, or changed) — it usually returns a *view* of the original array rather than a copy, so editing one can sometimes affect the other.

In [83]:
# reshape
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [85]:
# ravel
a3.ravel() #convert 3D and other D array to 1D array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

**`ravel()` vs `flatten()`:** both turn any-shaped array into 1D, but `ravel()` returns a *view* (shares memory with the original — editing one can edit the other) while `flatten()` always returns an independent *copy*. When unsure, `flatten()` is the safer default.

In [ ]:
grid = np.arange(6).reshape(2, 3)
view = grid.ravel()
view[0] = 99
print(grid)   # original changed too! ravel() shared memory

copy = grid.flatten()
copy[0] = -1
print(grid)   # original untouched -- flatten() made a real copy

**Reshape shortcuts & resize:**

In [ ]:
# use -1 in reshape to let NumPy figure out that dimension automatically
b = np.arange(12)
print(b.reshape(3, -1))   # NumPy computes -1 -> 4
print(b.reshape(-1, 6))   # NumPy computes -1 -> 2

In [ ]:
# reshape() refuses to change the total element count; resize() will (repeats data)
try:
    b.reshape(5, 5)
except ValueError as e:
    print("reshape error:", e)

print(np.resize(b, (4, 4)))   # 16 slots needed from 12 elements -> wraps around

## 12. 🔗 Stacking

Mnemonic: **h**stack = **h**orizontal, side-by-side (rows must match). **v**stack = **v**ertical, stacked on top of each other (columns must match).

In [86]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [87]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
## Horizontak stacking
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [89]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

**`np.concatenate()` — the general form of stacking:**

In [ ]:
# hstack/vstack are shortcuts for concatenate along a specific axis
print(np.concatenate((a4, a5), axis=1))   # same result as hstack
print(np.concatenate((a4, a5), axis=0))   # same result as vstack

In [ ]:
# stack multiple arrays into a brand-new extra dimension
np.stack((a4, a5))   # shape becomes (2, 3, 4) -- a "batch" of two (3,4) arrays

## 13. ✂️ Splitting

Splitting is the reverse of stacking — it cuts one array into several equal-sized pieces. The split count must divide evenly into that axis's length (e.g. `hsplit(a4, 4)` needs exactly 4 columns).

In [90]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [92]:
# vertical splitting
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [93]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

**`np.array_split()` — splitting into uneven pieces:**

In [ ]:
# hsplit/vsplit need the split count to divide evenly -- array_split doesn't
b = np.arange(10)
print(np.array_split(b, 3))   # 10 doesn't divide evenly into 3 -- extras go first

In [ ]:
# split at specific custom positions instead of evenly
print(np.split(b, [2, 5]))   # cut right before index 2, and right before index 5

## 14. ✅ Key Takeaways
- NumPy arrays are fixed-size, single-dtype grids — that's exactly what makes them fast.
- `*` and other operators act *element-wise* on arrays, unlike on Python lists.
- Attributes (`.shape`, `.ndim`, `.size`) describe an array; methods (`.reshape()`, `.astype()`) transform it.
- `axis=0` collapses down the rows (per-column result); `axis=1` collapses across the columns (per-row result).
- Indexing/slicing order is always left-to-right, outermost dimension first: `[row, col]` for 2D, `[depth, row, col]` for 3D.
- Boolean masks (`arr > 5`) and fancy indexing (`arr[[1,3,5]]`) are the main ways to filter/select data.
- Broadcasting lets NumPy combine arrays of different (but compatible) shapes without you manually copying data.
- Watch for silent gotchas: `.astype()` truncates instead of rounding, and very large integer operations can silently overflow.