### 🧰 NumPy's Most-Used Utility Functions

This notebook is a **cheat-sheet of individual NumPy functions** you'll reach for constantly in real data/ML code — each one gets a short beginner note plus worked examples you can reuse directly.

**What's covered, in order:**
1. 🔀 np.sort
2. ➕ np.append
3. 🔗 np.concatenate
4. 🧹 np.unique
5. 📐 np.expand_dims
6. 🎯 np.where
7. 📍 np.argmax / np.argmin
8. ➗ np.cumsum / np.cumprod
9. 📊 np.percentile / np.median
10. 📈 np.histogram
11. 🔢 np.corrcoef
12. ✅ np.isin
13. 🔄 np.flip
14. ✏️ np.put
15. 🗑️ np.delete
16. 🧩 Set functions (union1d, intersect1d, setdiff1d, setxor1d, isin)
17. ✂️ np.clip
18. 🔃 np.swapaxes
19. 🎲 np.random.uniform
20. 🔢 np.count_nonzero
21. 🧱 np.tile
22. 🔁 np.repeat
23. 🧪 np.allclose & np.array_equal
24. ✅ Key Takeaways

## 1. 🔀 np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [7]:
# code
import numpy as np
a = np.random.randint(1,100,15) ## 1D Array
a

array([ 5, 55, 47, 16, 65, 31, 28, 99, 82, 44, 67, 44, 90,  3, 90])

In [8]:
np.sort(a) # Ascending Order

array([ 3,  5, 16, 28, 31, 44, 44, 47, 55, 65, 67, 82, 90, 90, 99])

In [9]:
np.sort(a)[::-1] # descending Order 

array([99, 90, 90, 82, 67, 65, 55, 47, 44, 44, 31, 28, 16,  5,  3])

In [10]:
b = np.random.randint(1,100,24).reshape(6,4) ## 2D Array
b

array([[37, 79, 16, 73],
       [68, 76, 81, 39],
       [45,  4, 20, 81],
       [98, 23, 34, 21],
       [48, 26, 15, 71],
       [ 5, 91, 16,  9]])

In [11]:
np.sort(b,axis=0) ## column wise sorting

array([[ 5,  4, 15,  9],
       [37, 23, 16, 21],
       [45, 26, 16, 39],
       [48, 76, 20, 71],
       [68, 79, 34, 73],
       [98, 91, 81, 81]])

**Note:** `np.sort()` always returns a **new sorted array** — it never touches the original. To sort in place instead, use `array.sort()`.

In [12]:
np.sort(b, axis=1)   # each row sorted independently (contrast with axis=0 above, which sorts each column)

array([[16, 37, 73, 79],
       [39, 68, 76, 81],
       [ 4, 20, 45, 81],
       [21, 23, 34, 98],
       [15, 26, 48, 71],
       [ 5,  9, 16, 91]])

## 2. ➕ np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [13]:
# code
np.append(a,200)

array([  5,  55,  47,  16,  65,  31,  28,  99,  82,  44,  67,  44,  90,
         3,  90, 200])

In [16]:
b

array([[37, 79, 16, 73],
       [68, 76, 81, 39],
       [45,  4, 20, 81],
       [98, 23, 34, 21],
       [48, 26, 15, 71],
       [ 5, 91, 16,  9]])

In [17]:
np.append(b, np.ones((b.shape[0], 1)), axis=1)

array([[37., 79., 16., 73.,  1.],
       [68., 76., 81., 39.,  1.],
       [45.,  4., 20., 81.,  1.],
       [98., 23., 34., 21.,  1.],
       [48., 26., 15., 71.,  1.],
       [ 5., 91., 16.,  9.,  1.]])

In [ ]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[12.        , 52.        , 42.        ,  6.        ,  0.22006275],
       [29.        , 18.        , 47.        , 55.        ,  0.81740634],
       [61.        , 93.        , 83.        ,  9.        ,  0.89146072],
       [38.        , 63.        , 44.        , 85.        ,  0.84519124],
       [ 8.        , 87.        , 31.        , 72.        ,  0.24007274],
       [40.        , 71.        ,  2.        ,  7.        ,  0.48056374]])

**Note:** `np.append()` always returns a **flattened 1D array** unless you pass `axis=`. With `axis=`, whatever you're appending must match `b`'s shape along every other axis.

In [18]:
np.append(b, [[1,2,3,4]], axis=0)   # append a whole new row (must have 4 columns, same as b)

array([[37, 79, 16, 73],
       [68, 76, 81, 39],
       [45,  4, 20, 81],
       [98, 23, 34, 21],
       [48, 26, 15, 71],
       [ 5, 91, 16,  9],
       [ 1,  2,  3,  4]])

## 3. 🔗 np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [19]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [20]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

**Note:** every array being joined must have the **same shape** except along the axis you're joining on — the same rule `hstack`/`vstack` follow, just generalized to any axis and any number of arrays.

In [22]:
np.concatenate((c, d, c), axis=0)   # concatenate accepts more than 2 arrays at once

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5]])

## 4. 🧹 np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [23]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [24]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

**Note:** the result is always **sorted**. Pass `return_counts=True` to also see how many times each value showed up.

In [25]:
np.unique(e, return_counts=True)   # (unique values, how many times each one appears)

(array([1, 2, 3, 4, 5, 6]), array([2, 2, 2, 2, 2, 2]))

## 5. 📐 np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [26]:
# code
a.shape

(15,)

In [27]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [ ]:
np.expand_dims(a,axis=1)

array([[11],
       [53],
       [28],
       [50],
       [38],
       [37],
       [94],
       [92],
       [ 5],
       [30],
       [68],
       [ 9],
       [78],
       [ 2],
       [21]])

**Note:** this only adds a size-1 dimension — the underlying data never changes, just how it's organized. Handy when a function expects a specific number of dimensions (e.g. turning one image into a "batch of 1").

In [ ]:
print(np.expand_dims(a, axis=1).shape)               # (15, 1) instead of (15,)
print(np.squeeze(np.expand_dims(a, axis=0)).shape)   # squeeze() undoes it, back to (15,)

## 6. 🎯 np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 1,  6,  7, 10, 12]),)

In [ ]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([11,  0, 28, 50, 38, 37,  0,  0,  5, 30,  0,  9,  0,  2, 21])

In [ ]:
np.where(a%2 == 0,0,a)

array([11, 53,  0,  0,  0, 37,  0,  0,  5,  0,  0,  9,  0,  0, 21])

**Note:** with one argument, `np.where(cond)` gives you *positions*; with three arguments, `np.where(cond, x, y)` gives you *values* — pick whichever the situation needs.

In [ ]:
np.where(b > 50)   # same idea, now on a 2D array -> a (row_indices, col_indices) tuple

## 7. 📍 np.argmax / np.argmin

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [ ]:
# code
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
np.argmax(a)

6

In [ ]:
b

array([[12, 52, 42,  6],
       [29, 18, 47, 55],
       [61, 93, 83,  9],
       [38, 63, 44, 85],
       [ 8, 87, 31, 72],
       [40, 71,  2,  7]])

In [ ]:
np.argmax(b,axis=0)

array([2, 2, 2, 3])

In [ ]:
np.argmax(b,axis=1)

array([1, 3, 1, 3, 1, 1])

In [ ]:
# np.argmin
np.argmin(a)

13

**Note:** `argmax`/`argmin` return the **position** of the biggest/smallest value, not the value itself — combine with normal indexing to get the actual value.

In [ ]:
print(a[np.argmax(a)])   # the actual max value, found via its index
print(np.argmin(b, axis=1))   # position of the smallest value in each row

## 8. ➗ np.cumsum / np.cumprod

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
np.cumsum(a)

array([ 11,  64,  92, 142, 180, 217, 311, 403, 408, 438, 506, 515, 593,
       595, 616])

In [ ]:
b

array([[12, 52, 42,  6],
       [29, 18, 47, 55],
       [61, 93, 83,  9],
       [38, 63, 44, 85],
       [ 8, 87, 31, 72],
       [40, 71,  2,  7]])

In [ ]:
np.cumsum(b,axis=1)

array([[ 12,  64, 106, 112],
       [ 29,  47,  94, 149],
       [ 61, 154, 237, 246],
       [ 38, 101, 145, 230],
       [  8,  95, 126, 198],
       [ 40, 111, 113, 120]])

In [ ]:
np.cumsum(b)

array([  12,   64,  106,  112,  141,  159,  206,  261,  322,  415,  498,
        507,  545,  608,  652,  737,  745,  832,  863,  935,  975, 1046,
       1048, 1055])

**Note:** cumulative functions return an array the **same size** as the input — each position holds the running total up to (and including) that point.

In [ ]:
np.cumprod(b, axis=0)   # running product down each column

In [ ]:
# np.cumprod
np.cumprod(a)

array([                  11,                  583,                16324,
                     816200,             31015600,           1147577200,
               107872256800,        9924247625600,       49621238128000,
           1488637143840000,   101227325781120000,   911045932030080000,
       -2725393596491966464, -5450787192983932928, -3786066610405281792])

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

## 9. 📊 np.percentile / np.median

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
np.percentile(a,50)

37.0

In [ ]:
np.median(a)

37.0

**Note:** the 50th percentile is *always* the same number as the median — they're the same calculation by definition.

## 10. 📈 np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [ ]:
# code
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
np.histogram(a,bins=[0,50,100])

(array([9, 6]), array([  0,  50, 100]))

**Note:** `np.histogram` only computes the numbers (bin edges + counts) — it doesn't draw anything. Pair it with `plt.hist()` for an actual chart.

In [ ]:
np.histogram(a, bins=5)   # let NumPy pick 5 equal-width bins automatically, instead of specifying edges

## 11. 🔢 np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [ ]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

**Note:** the result is a correlation **matrix** — the diagonal is always 1 (everything correlates perfectly with itself); the number you usually want is the off-diagonal entry.

In [ ]:
np.corrcoef(salary, experience)[0, 1]   # just the salary-vs-experience correlation, pulled out of the matrix

## 12. ✅ np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [ ]:
# code
a


array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([50, 30])

**Note:** `np.isin()` returns a boolean mask the same shape as the first array — combine it with `[]` to pull out the matches, or negate it with `~` to get everything that's *not* in the list.

In [ ]:
a[~np.isin(a, items)]   # values in `a` that are NOT in `items`

## 13. 🔄 np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [ ]:
# code
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
np.flip(a)

array([21,  2, 78,  9, 68, 30,  5, 92, 94, 37, 38, 50, 28, 53, 11])

In [ ]:
b

array([[12, 52, 42,  6],
       [29, 18, 47, 55],
       [61, 93, 83,  9],
       [38, 63, 44, 85],
       [ 8, 87, 31, 72],
       [40, 71,  2,  7]])

In [ ]:
np.flip(b,axis=1)

array([[ 6, 42, 52, 12],
       [55, 47, 18, 29],
       [ 9, 83, 93, 61],
       [85, 44, 63, 38],
       [72, 31, 87,  8],
       [ 7,  2, 71, 40]])

**Note:** with no `axis`, `np.flip()` reverses *every* dimension at once. `axis=0` flips rows, `axis=1` flips columns — a more general version of the `[::-1]` slicing trick from the intro notebook.

In [ ]:
np.flip(b, axis=0)   # rows reversed top-to-bottom (contrast with axis=1 above, which flips columns)

## 14. ✏️ np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [ ]:
# code
a

array([110, 530,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21])

In [ ]:
np.put(a,[0,1],[110,530])

**Gotcha:** unlike almost every other function here, `np.put()` **mutates the array in place** and returns `None` — it changes `a` directly instead of handing back a new array.

In [ ]:
print(a)   # a itself has changed -- notice the first two values are now 110 and 530

# the more common/idiomatic way to do the same thing:
a[[0, 1]] = [110, 530]

## 15. 🗑️ np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [ ]:
# code
a

array([110, 530,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21])

In [ ]:
np.delete(a,[0,2,4])

array([530,  50,  37,  94,  92,   5,  30,  68,   9,  78,   2,  21])

**Note:** like most NumPy functions, `np.delete()` returns a **new array** — `a` itself is untouched. Pass `axis=0`/`axis=1` on a 2D array to delete whole rows/columns instead of flattened positions.

In [ ]:
np.delete(b, 1, axis=0)   # delete row at index 1 entirely

## 16. 🧩 Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.intersect1d(m,n)

array([3, 4, 5])

In [ ]:
np.setdiff1d(n,m)

array([6, 7])

In [ ]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [ ]:
m[np.isin(m,1)]   # np.in1d was removed in NumPy 2.x -- np.isin() is the replacement

array([1])

**Note:** these treat arrays like mathematical sets — order and duplicates don't matter, only which unique values are present. `np.in1d` shown above is **deprecated in NumPy 2.x**; `np.isin()` is the replacement and does the exact same job.

In [ ]:
np.isin(m, n)   # boolean mask -- which elements of m also appear anywhere in n

## 17. ✂️ np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [ ]:
# code
a

array([110, 530,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21])

In [ ]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 28, 50, 38, 37, 75, 75, 25, 30, 68, 25, 75, 25, 25])

**Note:** `a_min`/`a_max` can each be `None` if you only want to bound one side.

In [ ]:
np.clip(a, a_min=None, a_max=50)   # only cap the upper end, leave the lower end alone

## 18. 🔃 np.swapaxes

Swaps two axes of an array — a more flexible version of `.T` (which only swaps the *last two* axes on a 2D array). Useful for reordering dimensions on 3D+ arrays, e.g. switching an image between (height, width, channels) and (channels, height, width).

https://numpy.org/doc/stable/reference/generated/numpy.swapaxes.html

In [ ]:
np.swapaxes(b, 0, 1)   # same result as b.T for a 2D array

In [ ]:
arr3d = np.arange(24).reshape(2, 3, 4)
print(arr3d.shape)
print(np.swapaxes(arr3d, 0, 2).shape)   # (2,3,4) -> (4,3,2): axes 0 and 2 are swapped

## 19. 🎲 np.random.uniform

Generates random floats **evenly spread** between a low and high bound — unlike `np.random.random()`, which is locked to the 0-1 range. Useful for simulating continuous real-world values like temperatures or prices.

https://numpy.org/doc/stable/reference/generated/numpy.random.uniform.html

In [ ]:
np.random.uniform(10, 20, 5)   # 5 random floats, each between 10 and 20

In [ ]:
np.random.uniform(-1, 1, (2, 3))   # works with any shape too

## 20. 🔢 np.count_nonzero

Counts how many elements are **not zero** — or, combined with a condition like `a > 50`, how many elements satisfy it. Often clearer (and faster) than `len(a[a > 50])` or `np.sum(mask)`.

https://numpy.org/doc/stable/reference/generated/numpy.count_nonzero.html

In [ ]:
np.count_nonzero(a > 50)   # how many elements of a are greater than 50

In [ ]:
sample = np.array([[0, 1, 0], [2, 0, 3]])
np.count_nonzero(sample, axis=0)   # non-zero count per column

## 21. 🧱 np.tile

Repeats the **whole array** as a block, like copy-pasting it side by side / stacked. Compare with `np.repeat()` below, which repeats each *individual element* instead.

https://numpy.org/doc/stable/reference/generated/numpy.tile.html

In [ ]:
np.tile(np.array([1, 2, 3]), 3)   # the whole [1,2,3] block, repeated 3 times

In [ ]:
np.tile(np.array([[1, 2], [3, 4]]), (2, 3))   # tile a 2D block: 2x taller, 3x wider

## 22. 🔁 np.repeat

Repeats each **individual element** the given number of times, in place. Run this on the same input as `np.tile()` above and compare the outputs side by side — the difference becomes obvious.

https://numpy.org/doc/stable/reference/generated/numpy.repeat.html

In [ ]:
np.repeat(np.array([1, 2, 3]), 3)   # [1,1,1,2,2,2,3,3,3] -- compare with np.tile's [1,2,3,1,2,3,1,2,3]

In [ ]:
np.repeat(np.array([1, 2, 3]), [1, 2, 3])   # a different repeat count per element

## 23. 🧪 np.allclose & np.array_equal

Never compare floating-point arrays with `==` — tiny rounding errors make it unreliable. `np.allclose()` checks if two arrays are equal *within a small tolerance*; `np.array_equal()` checks for exact equality (fine for integers, risky for floats).

https://numpy.org/doc/stable/reference/generated/numpy.allclose.html

In [ ]:
print(0.1 + 0.2 == 0.3)          # False -- classic floating-point rounding trap
print(np.allclose(0.1 + 0.2, 0.3))   # True -- allclose forgives the tiny rounding error

In [ ]:
print(np.array_equal(np.array([1, 2, 3]), np.array([1, 2, 3])))   # True -- exact match
print(np.array_equal(np.array([1, 2, 3]), np.array([1, 2, 4])))   # False -- one value differs

## 24. ✅ Key Takeaways
- Most NumPy functions return a **new array** and leave the original untouched — `np.put()` is the exception here: it mutates in place.
- `axis=0` generally means "down the rows / per column", `axis=1` means "across the columns / per row" — the same convention from the intro notebook holds throughout.
- `argmax`/`argmin`/`where` give you **positions**; index back into the array (`a[np.argmax(a)]`) to get the actual **value**.
- `np.tile()` repeats the whole array as a block; `np.repeat()` repeats each element individually — easy to mix up.
- Set functions (`union1d`, `intersect1d`, `setdiff1d`, `setxor1d`, `isin`) treat arrays like mathematical sets — order and duplicates don't matter.
- `np.in1d` is deprecated/removed in modern NumPy — use `np.isin()` instead.
- Never compare floats with `==`; use `np.allclose()` to account for rounding error.